### ISSUE TITLE
Windows 7, no minimise

### ISSUE THREAD

**Issue by patcolyn** [klayveR/xenontrade#10]
Price checks never minimise on Windows 7.

Could not find any logging, can test further if prompted to.

For verification from the Reddit post, the app does auto focus, minimise and stay on top.

**Comment by klayveR** [comment]
I'm not sure what you mean. The price checks themselves are not supposed to minimize, the app itself is.

**Comment by klayveR** [comment]
Could not reproduce, please provide more information and reopen if this is still an issue.
