### ISSUE TITLE
Crashing On Search

### ISSUE THREAD

**Issue by WasabiCannon** [klayveR/xenontrade#14]
Win 10 Pro 64 bit.
When attempting to perform a search at all it will fail to provide any information and end up crashing.

**Comment by klayveR** [comment]
I need more information on this. What type of item is it? Is poe.ninja data loaded? Does it become unresponsive, simply close or does it actually crash?

**Comment by klayveR** [comment]
Ist this still an issue?

**Comment by klayveR** [comment]
Could not reproduce, please provide more information and reopen if this is still and issue.

**Comment by WasabiCannon** [comment]
Found the issue was due to the other PoE Trade macro that was loaded in the background.
