### ISSUE TITLE
Xenon stealing focus from PoE

### ISSUE THREAD

**Issue by XScorpion2** [klayveR/xenontrade#15]
Running PoE in Windowed Fullscreen, alt-tab out of PoE, then click back into PoE. PoE will have focus for 0.5-1s before focus is lost / stolen by Xenon. Xenon does not have Always focus PoE turned on.

**Comment by XScorpion2** [comment]
Good call, I do have Auto-Minimize enabled and disabling it does fix the issue.

**Comment by klayveR** [comment]
I'm leaving this here as a note for myself, should be in the next release.
[`win.showInactive()`](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winshowinactive)

**Comment by klayveR** [comment]
This is fixed in [v0.3.9](https://github.com/klayveR/xenontrade/releases/tag/v0.3.9).
