### ISSUE TITLE
Xenontrade can lose focus so that buttons aren't clickable

### ISSUE THREAD

**Issue by BlueManiac** [klayveR/xenontrade#16]
Quite hard to reproduce reliably. Easier without having auto-close on. This seems to happen because of a hidden area under the title is focusable for a short while sometimes. This triggers this.window.setIgnoreMouseEvents(true, {forward: true}) in gui._initializeWindowsTransparency without resetting the focus on reenter. Hovering over the title restores the focus.

removing:

```javascript
el.addEventListener("mouseenter", () => {
  // If entries div is empty
  if (!$.trim($(".entries").html())) {
    this.window.setIgnoreMouseEvents(true, {forward: true})
  }
});
```

Seems to fix the problem, but i'm not sure if this have any other side effects.

**Comment by klayveR** [comment]
The code mentioned above was temporarily removed in [v0.3.5](https://github.com/klayveR/xenontrade/releases/tag/v0.3.5). I'll close this issue, as the issue about the blocking non-clickthrough part is a separate problem. Feel free to reopen this issue if this specific problem wasn't fixed for you.

Thanks for the help again!
