### ISSUE TITLE
Magic items do not give any visible response

### ISSUE THREAD

**Issue by BlueManiac** [klayveR/xenontrade#17]
I understand that magic items aren't supported right know (or if they ever will be)

I got slightly confused when I tried to price-check some magic jewels and thought it was some kind of bug as nothing happened. Not until I actually read the code I understood why nothing happened.

I suggest that a message shows up that magic items aren't supported when you try to price check them. This might reduce unnecessary bug reports in the future.

**Comment by klayveR** [comment]
In [v0.3.7](https://github.com/klayveR/xenontrade/releases/tag/v0.3.7), the red indicator will flash in the menu bar if an item price is unavailable or the item is not supported. I decided against showing a message when an item is unsupported, as the list could become cluttered quickly that way.

Thanks for the suggestion!
