### ISSUE TITLE
Always focus poe makes it difficult to use the settings

### ISSUE THREAD

**Issue by Aerinx** [klayveR/xenontrade#19]
When you have that enabled the game is focused after every click, making it hard to use sliders, buttons, etc. Suggestion: disable that feature when settings is open.

**Comment by klayveR** [comment]
I just checked the code, since the option should not apply when in the settings menu as you suggested and found a bug that caused this behaviour. Will be fixed very soon, thanks for the bug report!

**Comment by klayveR** [comment]
This is fixed in [v0.3.8](https://github.com/klayveR/xenontrade/releases/tag/v0.3.8).

**Comment by Aerinx** [comment]
Thank you <3
