### ISSUE TITLE
Fix: Handle 503 errors instead of showing in price checker

### ISSUE THREAD

**Issue by kevintoombs** [klayveR/xenontrade#4]
Right now, if the price checker gets a 503 response, it just puts the entire HTML result into the price checker window, causing the screen to fill up with ugly unparsed HTML. Hopefully we can get a fix for this so it just displays something like "Gateway Timed Out (503)" instead.

**Comment by klayveR** [comment]
In [v0.3.7](https://github.com/klayveR/xenontrade/releases/tag/v0.3.7), those errors will no longer show in the UI, instead they are being logged into the newly added logfile. That being said, as of right now it will still log the whole unparsed HTML as I have no idea what the structure of the error is (or if it's actually just plain HTML).

I'll keep this issue opened until someone who encounters this error can give some more insight by posting what has been logged. Thanks!

**Comment by klayveR** [comment]
Fixed for all requests in [v0.4.1](https://github.com/klayveR/xenontrade/releases/tag/v0.4.1).
