### ISSUE TITLE
Chat function have disappeared

### ISSUE THREAD

**Issue by feydreva** [klayveR/xenontrade#49]
I re-installed fully my computer.

I always download the latest version of Xenontrade. 

But, before, like 2 weeks ago, I had a version of Xenontrade that would ask for the path of poe, and would allow chat command, like reply / thanks / sold

On this version. it is not present anymore.
What do i have to do to get the chat function back ???

**Comment by klayver** [comment]
Are you using the [alpha version](https://github.com/klayveR/xenontrade/releases/tag/v0.5.0-alpha)?

**Comment by feydreva** [comment]
I was not ! that s why.
Thanks :)
